from correlcalc import *
bins = np.arange(0.001,0.051,0.001)
binspar = np.arange(0.001,0.051,0.001)
binsper = np.arange(0.01,1.01,0.01)
acorrdr12flcdmcmn2x=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',bins,bins,randfile='/usr3/vstr/yrohin/randcat_DR12_CMN2x.dat',vtype='sigpi',estimator='ls',weights='eq')
#acorrdr12flcdmcmnsmu2x=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',binspar,binsper,randfile='/usr3/vstr/yrohin/randcat_DR12_CMN2x.dat',vtype='smu',estimator='ls',weights='eq')
print("---------------------------------------------------------------------------------")
print("Calulating for Rh=ct")
acorrdr12flcdmcmn2x=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',bins,bins,randfile='/usr3/vstr/yrohin/randcat_DR12_CMN2x.dat',vtype='sigpi',estimator='ls',weights='eq',cosmology='lc')
#acorrdr12flcsmucmn=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',binspar,binsper,randfile='/usr3/vstr/yrohin/randcat_DR12_CMN2x.dat',vtype='smu',estimator='ls',weights='eq',cosmology='lc')
print("---------------------------------------------------------------------------------")
print("Calculating for Milne")
acorrdr12fmilnecmn2x=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',bins,bins,randfile='/usr3/vstr/yrohin/randcat_DR12_CMN2x.dat',vtype='sigpi',estimator='ls',weights='eq',cosmology='lc',geometry='open')
print("---------------------------------------------------------------------------------")
#acorrdr12fmilnesmucmn=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',binspar,binsper,randfile='/usr3/vstr/yrohin/randcat_DR12_CMN2x.dat',vtype='smu',estimator='ls',weights='eq',cosmology='lc',geometry='open')
