from correlcalc import *
bins = np.arange(0.002,0.052,0.002)
acorrdr12flcdmcmn=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',bins,bins,randfile='/usr3/vstr/yrohin/Downloads/random0_DR12v5_CMASS_North.fits',vtype='sigpi',estimator='ls',weights='eq')
print("-------------------------------------")
print("-------------------------------------")
print("Calulating for sflat-mu")
binspar = np.arange(0.002,0.052,0.002)
binsper = np.arange(0.05,1.05,0.05) 
acorrdr12flcdmsmucmn=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',binspar,binsper,randfile='/usr3/vstr/yrohin/Downloads/random0_DR12v5_CMASS_North.fits',vtype='smu',estimator='ls',weights='eq')
print("-------------------------------------")
acorrdr12flcdmcmn=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',bins,bins,randfile='/usr3/vstr/yrohin/Downloads/random0_DR12v5_CMASS_North.fits',vtype='sigpi',estimator='ls',weights=True)
print("-------------------------------------")
acorrdr12flcdmsmucmn=atpcf('/usr3/vstr/yrohin/Downloads/galaxy_DR12v5_CMASS_North.fits',binspar,binsper,randfile='/usr3/vstr/yrohin/Downloads/random0_DR12v5_CMASS_North.fits',vtype='smu',estimator='ls',weights=True)
#print("Calulating for Rh=ct flat lc s-mu")
#binspar = np.arange(0.001,0.02,0.001)
#binsper = np.arange(0.05,1.05,0.05)
#acorrdr7flcsmu=atpcf('/usr3/vstr/yrohin/Downloads/DR7-Full.ascii',binspar,binsper,randfile='/usr3/vstr/yrohin/Downloads/randcat_DR7_2xw.dat',vtype='smu',estimator='ls',weights='eq',cosmology='lc',geometry='flat')
#print("-------------------------------------")
#acorrdr7flcsmu=atpcf('/usr3/vstr/yrohin/Downloads/DR7-Full.ascii',binspar,binsper,randfile='/usr3/vstr/yrohin/Downloads/randcat_DR7_2xw.dat',vtype='smu',estimator='ls',weights=True,cosmology='lc',geometry='flat')

#print("-------------------------------------")
#print("Calulating for Milne open lc s-mu")
#binspar = np.arange(0.001,0.02,0.001)
#binsper = np.arange(0.05,1.05,0.05)
#acorrdr7olcsmu=atpcf('/usr3/vstr/yrohin/Downloads/DR7-Full.ascii',binspar,binsper,randfile='/usr3/vstr/yrohin/Downloads/randcat_DR7_2xw.dat',vtype='smu',estimator='ls',weights='eq',cosmology='lc',geometry='open')
#print("-------------------------------------")
#acorrdr7olcsmu=atpcf('/usr3/vstr/yrohin/Downloads/DR7-Full.ascii',binspar,binsper,randfile='/usr3/vstr/yrohin/Downloads/randcat_DR7_2xw.dat',vtype='smu',estimator='ls',weights=True,cosmology='lc',geometry='open')
